#!/usr/bin/env node
// Maintenance tool: bake the reading list (READING_LIST in js/books.js)
// into books/index.html as static HTML, so the list is visible to search
// engines and visitors without JavaScript.
//
// Usage:
//   node scripts/render-books.js           # regenerate books/index.html
//   node scripts/render-books.js --check   # exit 1 if the file is stale
//
// A unit test runs the equivalent of --check, so CI fails if READING_LIST
// changes without re-running this script.

const fs = require('node:fs');
const path = require('node:path');
const { readingListHtml } = require('../js/books.js');

const FILE = path.join(__dirname, '..', 'books', 'index.html');
const BEGIN = '<!-- BEGIN reading-list: generated by scripts/render-books.js; edit js/books.js instead -->';
const END = '<!-- END reading-list -->';

const current = fs.readFileSync(FILE, 'utf8');
const beginAt = current.indexOf(BEGIN);
const endAt = current.indexOf(END);
if (beginAt === -1 || endAt === -1 || endAt < beginAt) {
    console.error(`render-books: marker comments not found in ${FILE}`);
    process.exit(1);
}

const updated =
    current.slice(0, beginAt + BEGIN.length) +
    `${readingListHtml()}\n            ` +
    current.slice(endAt);

if (process.argv.includes('--check')) {
    if (updated !== current) {
        console.error('books/index.html is stale — run: node scripts/render-books.js');
        process.exit(1);
    }
    console.log('books/index.html is up to date');
} else if (updated === current) {
    console.log('books/index.html already up to date');
} else {
    fs.writeFileSync(FILE, updated);
    console.log('books/index.html regenerated');
}
